
(define-rewrite-system regex
  ((v (empty)) --> (false))
  ((v (epsilon)) --> (true))
  ((v (symbol _)) --> (false))
  ((v (seq r s)) --> (and (v r) (v s)))
  ((v (kleene r)) --> (true))
  ((v (or r s)) --> (or (v r) (v s)))

  ((v1 r) --> (v1r (v r)))
  ((v1r (true)) --> (epsilon))
  ((v1r (false)) --> (empty))

  ((d a (empty)) --> (empty))
  ((d a (epsilon)) --> (empty))
  ((d a (any)) --> (epsilon))
  ((d a (symbol a1)) where (eq? a a1) --> (epsilon))
  ((d a (symbol a1)) --> (empty))
;  ((d a (symbol a1)) where (not (eq? a a1)) --> (empty))
  ((d a (seq r s)) --> (or (seq (d a r) s) (seq (v1 r) (d a s))))
  ((d a (kleene r)) --> (seq (d a r) (kleene r)))
  ((d a (or r s)) --> (or (d a r) (d a s))))

(define-rewrite-system regex-simplify
  ((kleene (kleene r)) --> (kleene r))
  ((or (epsilon) (seq r (kleene r))) --> (kleene r))
  ((or (seq r (kleene r)) (epsilon)) --> (kleene r))
  ((seq (empty) r) --> (empty))
  ((seq r (empty)) --> (empty))
  ((seq (epsilon) r) --> r)
  ((seq r (epsilon)) --> r)
  ((or (empty) r) --> r)
  ((or r (empty)) --> r)
  ((or r r) --> r)
  ((seq (seq a b) c) --> (seq a (seq b c)))
  ((or (or a b) c) --> (or a (or b c)))
  ((seq (or r1 r2) r) --> (or (seq r1 r) (seq r2 r)))
  ((seq r (or r1 r2)) --> (or (seq r r1) (seq r r2))))


;(display (regex-simp (regex '(d #\c (kleene (symbol #\c))))))

;; (merge ((branch (decons)
;; 		((branch (compare-equal? 'or)
;; 			 ((branch (decons)
;; 				  ((branch (decons)
;; 					   ((branch (compare-equal? 'empty)
;; 						    ((branch (compare-equal? '())
;; 							     ((branch (decons)
;; 								      ((branch (bind r)
;; 									       ((branch (compare-equal? '())
;; 											((branch (guard #t)
;; 												 ((branch (execute r) ())))))))))))))))
;; 				   (branch (bind r)
;; 					   ((branch (decons)
;; 						    ((branch (decons)
;; 							     ((branch (compare-equal? 'empty)
;; 								      ((branch (compare-equal? '())
;; 									       ((branch (compare-equal? '())
;; 											((branch (guard #t)
;; 												 ((branch (execute r) ())))))))))))))))))))))))
